weather:
    latitude: 31.3562
    longitude: -113.526
areas:
    - Corona del Sol
    - Costa Diamente
    - Las Conchas
    - Las Palmas
    - Mirador
    - Playa Encanto
    - Sandy Beach
cache_population_searches:
    - address:
        country: 'MX'
